'''
Find all possible combinations by picking one item from each list

Input: [
    ['quick', 'slow'],
    ['brown', 'red'],
    ['fox', 'dog']
]

Output:
    quick brown fox
    quick brown dog
    quick red fox
    quick red dog
    slow brown fox
    slow brown dog
    slow red fox
    slow red dog
'''


def combinations(lists):
    """Returns a list with all possible lists generated by choosing
    one item from each list"""
    if not lists:
        return [[]]
    combination_list = []
    for item in lists[0]:
        for combination in combinations(lists[1:]):
            combination_list.append([item] + combination)
    return combination_list


lists = [
    ['quick', 'slow'],
    ['brown', 'red'],
    ['fox', 'dog']
]

for combination in combinations(lists):
    for s in combination:
        print s + ' ',
    print
